const TYPES=[["W","河川"],["BNV","營建噪音"],["NV","噪音振動"],["LFN","低頻噪音"],["WU","放流水"],["WG","地下水"],["A","空氣"],["S","土壤"],["DS","底泥"],["WD","飲用水"]];
const app=document.querySelector('#app'),homeBtn=document.querySelector('#homeBtn'),saveStatus=document.querySelector('#saveStatus'),toastEl=document.querySelector('#toast'),navHome=document.querySelector('#navHome'),navAdd=document.querySelector('#navAdd'),navExport=document.querySelector('#navExport'),navSettings=document.querySelector('#navSettings');let db,state={view:'home'};const pad=n=>String(n).padStart(2,'0'),uid=()=>{try{if(window.crypto&&typeof window.crypto.randomUUID==='function')return window.crypto.randomUUID()}catch(e){}return Date.now().toString(36)+Math.random().toString(36).slice(2)},esc=s=>String(s??'').replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':'&quot;',"'":"&#39;"}[m]));
function toast(t){toastEl.textContent=t;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),1600)}
function openDB(){return new Promise((res,rej)=>{let settled=false;const fail=e=>{if(!settled){settled=true;rej(e instanceof Error?e:new Error('IndexedDB unavailable'))}};try{const r=indexedDB.open('efa-db',3);const timer=setTimeout(()=>fail(new Error('IndexedDB timeout')),3500);r.onupgradeneeded=()=>{const d=r.result;let ps;if(!d.objectStoreNames.contains('projects'))ps=d.createObjectStore('projects',{keyPath:'id'});let ph;if(!d.objectStoreNames.contains('photos'))ph=d.createObjectStore('photos',{keyPath:'id'});else ph=r.transaction.objectStore('photos');if(!ph.indexNames.contains('byPoint'))ph.createIndex('byPoint','pointKey')};r.onsuccess=()=>{clearTimeout(timer);if(!settled){settled=true;res(r.result)}};r.onerror=()=>{clearTimeout(timer);fail(r.error)};r.onblocked=()=>{clearTimeout(timer);fail(new Error('IndexedDB blocked'))}}catch(e){fail(e)}})}
const reqP=r=>new Promise((res,rej)=>{r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)}),store=(n,m='readonly')=>db.transaction(n,m).objectStore(n);
const PROJECTS_KEY='efa-projects-v3';
function readProjects(){try{return JSON.parse(localStorage.getItem(PROJECTS_KEY)||'[]')}catch(e){return[]}}
function writeProjects(list){localStorage.setItem(PROJECTS_KEY,JSON.stringify(list))}
async function getProjects(){return readProjects()}
async function getProject(id){return readProjects().find(p=>p.id===id)||null}
async function saveProject(p){saveStatus.textContent='💾 儲存中…';p.updatedAt=Date.now();const list=readProjects();const i=list.findIndex(x=>x.id===p.id);if(i>=0)list[i]=p;else list.push(p);writeProjects(list);saveStatus.textContent='✅ 已儲存'}
async function deleteProjectRecord(id){writeProjects(readProjects().filter(p=>p.id!==id))}
async function photos(pointKey){if(!db)return[];try{return await reqP(store('photos').index('byPoint').getAll(pointKey))}catch(e){console.error(e);return[]}}
homeBtn.onclick=()=>{state={view:'home'};render()};
navHome.onclick=()=>{state={view:'home'};render()};
navAdd.onclick=()=>{state={view:'create',selected:[]};render()};
navExport.onclick=async()=>{
  if(!state.projectId)return toast('請先開啟一個專案');
  state={view:'export',projectId:state.projectId};render();
};
navSettings.onclick=async()=>{
  if(state.view!=='project'&&state.view!=='point')return toast('請先開啟一個專案');
  state={view:'edit',projectId:state.projectId};render();
};
function updateNav(){
  [navHome,navAdd,navExport,navSettings].forEach(x=>x.classList.remove('active'));
  if(state.view==='home')navHome.classList.add('active');
  else if(state.view==='create')navAdd.classList.add('active');
  else if(state.view==='edit')navSettings.classList.add('active');
  else if(state.view==='export')navExport.classList.add('active');
}
async function render(){updateNav();homeBtn.classList.toggle('hidden',state.view==='home');if(state.view==='home')return home();if(state.view==='create')return createPage();if(state.view==='project')return projectPage();if(state.view==='point')return pointPage();if(state.view==='edit')return editPage();if(state.view==='export')return exportPage()}
async function home(){const ps=(await getProjects()).sort((a,b)=>b.updatedAt-a.updatedAt);app.innerHTML=`<section class="card"><button class="btn" id="new">＋ 建立新專案</button></section><section class="card"><div class="titleRow"><h2>我的專案</h2><span class="muted">${ps.length} 個</span></div><div class="grid" id="list"></div></section>`;document.querySelector('#new').onclick=()=>{state={view:'create',selected:[]};render()};const l=document.querySelector('#list');if(!ps.length){l.innerHTML='<div class="empty">尚未建立專案</div>';return}for(const p of ps){let done=0,total=0;for(const t of p.types){total+=t.points;for(let i=1;i<=t.points;i++)if((await photos(`${p.id}:${t.id}:${i}`)).length)done++}const b=document.createElement('button');b.className='projectCard';b.innerHTML=`<span class="projectNo">${esc(p.number)}</span><span class="muted">${p.types.length} 個測項<br>${done}/${total} 點完成</span>`;b.onclick=()=>{state={view:'project',projectId:p.id};render()};l.appendChild(b)}}
function createPage(){app.innerHTML=`<section class="card"><div class="titleRow"><h2>建立專案</h2></div><div class="field"><label>專案編號</label><input id="projectNo" inputmode="numeric" placeholder="例如 13530"></div></section><section class="card"><div class="titleRow"><h3>選擇測項（可複選）</h3></div><div class="typeChoices">${TYPES.map(([c,n])=>`<label class="choice"><input type="checkbox" value="${c}"><span><b>${n}</b> (${c})</span></label>`).join('')}</div></section><section id="selectedSettings"></section><button class="btn" id="createBtn">建立專案</button>`;document.querySelectorAll('.choice input').forEach(x=>x.onchange=renderSelectedSettings);document.querySelector('#createBtn').onclick=createProject}
function renderSelectedSettings(){const codes=[...document.querySelectorAll('.choice input:checked')].map(x=>x.value),host=document.querySelector('#selectedSettings');host.innerHTML=codes.map(c=>{const [code,name]=TYPES.find(x=>x[0]===c);return `<section class="card" data-code="${code}"><h3>${name} (${code})</h3><div class="settings"><div class="field"><label>次數</label><input class="run" inputmode="numeric" value="1"></div><div class="field"><label>點位數</label><select class="points">${[1,2,3,4,5,6,7,8,9,10].map(n=>`<option>${n}</option>`).join('')}<option value="other">其他…</option></select></div></div><div class="field other hidden"><label>其他點位數</label><input class="otherInput" inputmode="numeric" min="1" max="99"></div></section>`}).join('');host.querySelectorAll('select.points').forEach(s=>s.onchange=()=>s.closest('.card').querySelector('.other').classList.toggle('hidden',s.value!=='other'))}
async function createProject(){const number=document.querySelector('#projectNo').value.trim();if(!number)return toast('請輸入專案編號');const cards=[...document.querySelectorAll('#selectedSettings .card')];if(!cards.length)return toast('請至少選一個測項');const types=[];for(const c of cards){const code=c.dataset.code,[,name]=TYPES.find(x=>x[0]===code),run=c.querySelector('.run').value.trim(),sel=c.querySelector('select.points').value,points=Number(sel==='other'?c.querySelector('.otherInput').value:sel);if(!run||!Number.isInteger(points)||points<1||points>99)return toast('請確認次數與點位數');types.push({id:uid(),code,name,run,points})}const p={id:uid(),number,types,createdAt:Date.now(),updatedAt:Date.now()};await saveProject(p);state={view:'project',projectId:p.id};render()}
async function projectPage(){const p=await getProject(state.projectId);app.innerHTML=`<section class="card"><div class="titleRow"><div><h2>專案 ${esc(p.number)}</h2><div class="muted">${p.types.length} 個測項</div></div><button class="btn danger" id="delP">刪除專案</button></div></section><div id="types"></div>`;document.querySelector('#delP').onclick=async()=>{if(!confirm('確定刪除這個專案？\n手機相簿原圖不會被刪除。'))return;const all=await reqP(store('photos').getAll()),s=store('photos','readwrite');all.filter(x=>x.projectId===p.id).forEach(x=>s.delete(x.id));await deleteProjectRecord(p.id);state={view:'home'};render()};const host=document.querySelector('#types');for(const t of p.types){let done=0,count=0;for(let i=1;i<=t.points;i++){const a=await photos(`${p.id}:${t.id}:${i}`);count+=a.length;if(a.length)done++}const sec=document.createElement('section');sec.className='card';sec.innerHTML=`<div class="titleRow"><div><h3>${esc(t.name)} ${esc(t.code)}${esc(t.run)}</h3><div class="muted">${done}/${t.points} 點完成 · ${count} 張照片</div></div><span class="badge ${done===t.points?'ok':'no'}">${done===t.points?'完成':'進行中'}</span></div><div class="points"></div><div class="actions"><button class="btn export">📦 匯出 ZIP</button></div>`;host.appendChild(sec);const g=sec.querySelector('.points');for(let i=1;i<=t.points;i++){const a=await photos(`${p.id}:${t.id}:${i}`),b=document.createElement('button');b.className=`pointCard ${a.length?'done':'missing'}`;let thumb='<div class="thumb"></div>';if(a[0])thumb=`<img class="thumb" src="${URL.createObjectURL(a[0].blob)}">`;b.innerHTML=`${thumb}<div class="pointHead"><span>${pad(i)}</span><span>${a.length?'🟢':'🔴'}</span></div><div class="muted">${a.length} 張</div>`;b.onclick=()=>{state={view:'point',projectId:p.id,typeId:t.id,point:i};render()};g.appendChild(b)}sec.querySelector('.export').onclick=()=>exportType(p,t)}}
async function pointPage(){const p=await getProject(state.projectId),t=p.types.find(x=>x.id===state.typeId),key=`${p.id}:${t.id}:${state.point}`,arr=await photos(key);app.innerHTML=`<section class="card"><div class="titleRow"><div><h2>${esc(p.number)}${esc(t.code)}${esc(t.run)}-${pad(state.point)}</h2><div class="muted">${arr.length} 張照片</div></div></div><label class="btn" style="display:block;text-align:center">📷 從相簿選取照片<input type="file" id="picker" accept="image/*" multiple hidden></label><div class="photos" id="photos"></div><div class="actions"><button class="btn secondary" id="back">返回</button></div></section>`;document.querySelector('#back').onclick=()=>{state={view:'project',projectId:p.id};render()};document.querySelector('#picker').onchange=e=>{const fs=[...e.target.files];if(!fs.length)return;saveStatus.textContent='💾 儲存中…';if(!db){toast('此瀏覽器無法保存照片，請改用 Safari 開啟');return}const s=store('photos','readwrite');fs.forEach(f=>s.put({id:uid(),projectId:p.id,typeId:t.id,point:state.point,pointKey:key,blob:f,name:f.name,createdAt:Date.now()}));s.transaction.oncomplete=()=>{saveStatus.textContent='✅ 已儲存';render()}};const host=document.querySelector('#photos');if(!arr.length)host.innerHTML='<div class="empty" style="grid-column:1/-1">尚未加入照片</div>';for(const ph of arr){const d=document.createElement('div');d.className='photo';const u=URL.createObjectURL(ph.blob);d.innerHTML=`<img src="${u}"><button class="remove">×</button>`;d.querySelector('.remove').onclick=async()=>{await reqP(store('photos','readwrite').delete(ph.id));render()};host.appendChild(d)}}
function mailSubject(projectNo){const d=new Date(),y=d.getFullYear(),m=pad(d.getMonth()+1),day=pad(d.getDate());return `${projectNo}_${y}/${m}/${day}`}
async function exportPage(){
 const p=await getProject(state.projectId);if(!p)return state={view:'home'},render();
 const rows=[];
 for(const t of p.types){let count=0,done=0;for(let i=1;i<=t.points;i++){const a=await photos(`${p.id}:${t.id}:${i}`);count+=a.length;if(a.length)done++}rows.push({t,count,done})}
 const subject=mailSubject(p.number);
 app.innerHTML=`<section class="card exportPanel"><div class="titleRow"><div><h2>寄回公司</h2><div class="muted">專案 ${esc(p.number)}</div></div></div><div class="subjectBox"><div class="muted">郵件主旨</div><div class="subjectText" id="mailSubject">${esc(subject)}</div><button class="btn secondary copySubject" id="copySubject">📋 複製主旨</button></div></section><section class="card"><div class="titleRow"><h3>勾選今天完成的測項</h3><span class="muted">有照片的已預選</span></div><div class="exportChoices">${rows.map(({t,count,done})=>`<label class="exportChoice"><input type="checkbox" value="${t.id}" ${count?'checked':''}><span><b>${esc(t.name)} ${esc(t.code)}${esc(t.run)}</b><small>${done}/${t.points} 點 · ${count} 張</small></span></label>`).join('')}</div><div class="actions"><button class="btn secondary" id="selectAll">全選</button><button class="btn secondary" id="clearAll">清除</button></div></section><section class="card"><button class="btn mailSend" id="exportSelected">📧 建立附件並寄送</button><div class="muted exportHint">會建立 1 個 ZIP：${esc(p.number)}.zip → photo → 所有勾選照片</div><div class="actions"><button class="btn secondary" id="back">← 返回專案</button></div></section>`;
 document.querySelector('#copySubject').onclick=async()=>{try{await navigator.clipboard.writeText(subject);toast('主旨已複製')}catch(e){const ta=document.createElement('textarea');ta.value=subject;document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();toast('主旨已複製')}};
 document.querySelector('#selectAll').onclick=()=>document.querySelectorAll('.exportChoice input').forEach(x=>x.checked=true);
 document.querySelector('#clearAll').onclick=()=>document.querySelectorAll('.exportChoice input').forEach(x=>x.checked=false);
 document.querySelector('#back').onclick=()=>{state={view:'project',projectId:p.id};render()};
 document.querySelector('#exportSelected').onclick=()=>exportSelectedProject(p,subject);
}
async function exportSelectedProject(p,subject){
 const ids=[...document.querySelectorAll('.exportChoice input:checked')].map(x=>x.value);if(!ids.length)return toast('請至少勾選一個測項');
 const selected=p.types.filter(t=>ids.includes(t.id)),entries=[],missing=[];
 for(const t of selected){for(let i=1;i<=t.points;i++){const a=await photos(`${p.id}:${t.id}:${i}`);if(!a.length)missing.push(`${t.code}${t.run}-${pad(i)}`);for(let j=0;j<a.length;j++){const ext=(a[j].name.split('.').pop()||'jpg').toLowerCase(),base=`${p.number}${t.code}${t.run}-${pad(i)}`,name=a.length===1?`${base}.${ext}`:`${base}-${j+1}.${ext}`;entries.push({name:`photo/${name}`,blob:a[j].blob})}}}
 if(!entries.length)return toast('勾選的測項沒有照片');
 if(missing.length&&!confirm(`尚未完成點位：\n${missing.join('、')}\n\n仍要寄送嗎？`))return;
 saveStatus.textContent='📦 正在打包…';const b=await zip(entries),fileName=`${p.number}.zip`,file=new File([b],fileName,{type:'application/zip'});let shared=false;
 try{if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){await navigator.share({files:[file],title:subject});shared=true}}catch(e){if(e&&e.name==='AbortError'){saveStatus.textContent='✅ 已儲存';return}}
 if(!shared){const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=fileName;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),30000)}
 saveStatus.textContent='✅ 已儲存';toast(shared?'已開啟分享選單':'ZIP 已建立');
}
async function editPage(){
 const p=await getProject(state.projectId);if(!p)return state={view:'home'},render();
 app.innerHTML=`<section class="card"><div class="titleRow"><h2>專案設定</h2></div><div class="field"><label>專案編號</label><input id="editNo" value="${esc(p.number)}"></div></section><div id="editTypes">${p.types.map(t=>`<section class="card typeEdit" data-id="${t.id}"><h3>${esc(t.name)} (${esc(t.code)})</h3><div class="settings"><div class="field"><label>次數</label><input class="editRun" inputmode="numeric" value="${esc(t.run)}"></div><div class="field"><label>點位數</label><input class="editPoints" inputmode="numeric" min="1" max="99" value="${t.points}"></div></div></section>`).join('')}</div><button class="btn" id="saveEdit">儲存設定</button>`;
 document.querySelector('#saveEdit').onclick=async()=>{const number=document.querySelector('#editNo').value.trim();if(!number)return toast('請輸入專案編號');for(const box of document.querySelectorAll('.typeEdit')){const t=p.types.find(x=>x.id===box.dataset.id),run=box.querySelector('.editRun').value.trim(),points=Number(box.querySelector('.editPoints').value);if(!run||!Number.isInteger(points)||points<1||points>99)return toast('請確認次數與點位數');t.run=run;t.points=points}p.number=number;await saveProject(p);state={view:'project',projectId:p.id};render();toast('設定已更新')}
}
function crc32(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0)}return(c^0xffffffff)>>>0}const l16=n=>new Uint8Array([n&255,n>>>8&255]),l32=n=>new Uint8Array([n&255,n>>>8&255,n>>>16&255,n>>>24&255]);function cat(a){let n=a.reduce((s,x)=>s+x.length,0),o=new Uint8Array(n),p=0;for(const x of a){o.set(x,p);p+=x.length}return o}async function zip(entries){const enc=new TextEncoder(),loc=[],cen=[];let off=0;for(const e of entries){const name=enc.encode(e.name),data=new Uint8Array(await e.blob.arrayBuffer()),crc=crc32(data),l=cat([l32(0x04034b50),l16(20),l16(0),l16(0),l16(0),l16(0),l32(crc),l32(data.length),l32(data.length),l16(name.length),l16(0),name,data]);loc.push(l);cen.push(cat([l32(0x02014b50),l16(20),l16(20),l16(0),l16(0),l16(0),l16(0),l32(crc),l32(data.length),l32(data.length),l16(name.length),l16(0),l16(0),l16(0),l16(0),l32(0),l32(off),name]));off+=l.length}const cs=cen.reduce((s,x)=>s+x.length,0),end=cat([l32(0x06054b50),l16(0),l16(0),l16(entries.length),l16(entries.length),l32(cs),l32(off),l16(0)]);return new Blob([...loc,...cen,end],{type:'application/zip'})}
async function exportType(p,t){const entries=[],missing=[];for(let i=1;i<=t.points;i++){const a=await photos(`${p.id}:${t.id}:${i}`);if(!a.length)missing.push(pad(i));for(let j=0;j<a.length;j++){const ext=(a[j].name.split('.').pop()||'jpg').toLowerCase(),base=`${p.number}${t.code}${t.run}-${pad(i)}`,name=a.length===1?`${base}.${ext}`:`${base}-${j+1}.${ext}`;entries.push({name,blob:a[j].blob})}}if(!entries.length)return toast('尚未加入照片');if(missing.length&&!confirm(`尚未完成點位：${missing.join('、')}\n仍要匯出嗎？`))return;saveStatus.textContent='📦 正在打包…';const b=await zip(entries),fileName=`${p.number}${t.code}${t.run}.zip`,file=new File([b],fileName,{type:'application/zip'});let shared=false;try{if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){await navigator.share({files:[file],title:fileName});shared=true}}catch(e){if(e&&e.name==='AbortError'){saveStatus.textContent='✅ 已儲存';return}}if(!shared){const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=fileName;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),30000)}saveStatus.textContent='✅ 已儲存';toast(shared?'已開啟分享選單':'ZIP 已建立')}
(async()=>{
  app.innerHTML='<section class="card"><div class="empty">正在載入…</div></section>';
  try{db=await openDB()}catch(e){db=null;console.error(e);saveStatus.textContent='⚠️ 照片儲存受限';}
  try{await render()}catch(e){console.error(e);app.innerHTML='<section class="card"><h2>載入失敗</h2><p class="muted">請按下方按鈕重新載入。</p><button class="btn" onclick="location.reload()">重新載入</button></section>'}
  if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v=30').catch(()=>{});
})();
